CountDownShow/Models/Dictionary.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CountDownShow.Models
{
    public class Dictionary
    {
        public ArrayList AllWords { get; set; }

        public string NineWord { get; set; }

        public string LongestWord { get; set; }

        public string InputWord { get; set; }
    }
}

CountDownShow/Models/Score.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CountDownShow.Models
{
    public class Score
    {
        public int TotalScore { get; set; }

        public int RoundScore { get; set; }

        public int Round { get; set; }
    }
}

CountDownShow/Controllers/DictionaryController.cs
using CountDownShow.Models;
using CountDownShow.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CountDownShow.Controllers
{
    public class DictionaryController : Controller
    {
        private IDictionaryService _dictionaryService;
        private IScoreService _scoreService;
        Score _score;
        int _round;
        public DictionaryController(IDictionaryService dictionaryService, IScoreService scoreService)
        {
            _dictionaryService = dictionaryService;
            _scoreService = scoreService;
            _score = getScore().Result;
            _round = _score.Round;
        }
        public async Task<Score> getScore()
        {
            return await _scoreService.getSelf();
        }
        public async Task<IActionResult> Index(string welcome)
        {
            if (_score.Round != 5)
            {
                if (_score.Round == 6)
                {
                    _score.Round = 1;
                    _score.TotalScore = 0;
                }
                ViewBag.Title = "Count Down Game";
                _dictionaryService.getSelf().InputWord = "";
                _dictionaryService.getSelf().LongestWord = "";
                if (welcome == null)
                {
                    ViewBag.welcome = "Welcom Count Down Game,Please input at least 3 different vowels and 4 different consonants";
                }
                else
                {
                    ViewBag.welcome = welcome;
                }
                Dictionary dictionary = _dictionaryService.getSelf();
                return View(dictionary);
            }
            else {
                return RedirectToAction(nameof(Finish));
            }
        }

        //[HttpPost]
        public async Task<IActionResult> AddNineWords(Dictionary ninewords)
        {
            if (ModelState.IsValid)
            {
                await _dictionaryService.setNineWords(ninewords.NineWord);
            }
            if (_dictionaryService.checkNineWords())
            {
                return RedirectToAction(nameof(CountDown));
            }
            else 
            {
                return RedirectToAction(nameof(Index),new { welcome = "Please input at least 3 different vowels and 4 different consonants" });
            }
        }

        public IActionResult CountDown()
        {
            ViewBag.Title = "Count Down Game";
            ViewBag.text = "You have 30 seconds";
            ViewBag.nineWord = _dictionaryService.getNineWords().ToString().ToUpper();
            Dictionary dictionary = _dictionaryService.getSelf();
            return View(dictionary);
        }

        public IActionResult Finish()
        {
            ViewBag.Title = "Count Down Game";
            ViewBag.TotalScore = "Game Over. Your total score is " + _score.TotalScore;
            return View();
        }

        public async Task<IActionResult> InputAnswer(Dictionary answer)
        {
            if (ModelState.IsValid)
            {
                _dictionaryService.setInputWord(answer.InputWord);
                await _dictionaryService.setLongestWord();
                return RedirectToAction(nameof(Result));
            }
            else {
                return RedirectToAction(nameof(CountDown));
            }
        }

        public IActionResult Result()
        {
            ViewBag.Title = "Count Down Game";
            if (_dictionaryService.checkInputWord())
            {
                ViewBag.answer = "Good job, your answer is " + _dictionaryService.getSelf().InputWord;
                if (_dictionaryService.getSelf().InputWord.Length == 9)
                {
                    _score.RoundScore = 18;
                }
                else
                {
                    _score.RoundScore = _dictionaryService.getSelf().InputWord.Length;
                }
            }
            else {
                ViewBag.answer = "Failed, your answer " + _dictionaryService.getSelf().InputWord + " isn't a  word or not belong the Nine word";
                _score.RoundScore = 0;
            }
            ViewBag.longestWord = "The Longest word is " + _dictionaryService.getSelf().LongestWord;
            ViewBag.roundScore = "This round score is " + _score.RoundScore;
            _scoreService.AddScore();
            Dictionary dictionary = _dictionaryService.getSelf();
            return View(dictionary);
        }

        public IActionResult NextRound()
        {
            _score.Round = _score.Round + 1;
            return RedirectToAction(nameof(Index));
            
        }
    }
}

CountDownShow/ViewComponents/ScoreViewComponent.cs
using CountDownShow.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CountDownShow.ViewComponents
{
    public class ScoreViewComponent:ViewComponent
    {
        private readonly IScoreService _scoreService;
        public ScoreViewComponent(IScoreService scoreService)
        {
            _scoreService = scoreService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var score = await _scoreService.getSelf();
            return View(score);
        }
    }
}

CountDownShow/Views/Dictionary/Finish.cshtml
@using CountDownShow.Models

    <div class="text-center">
        <div class="text-center">
            <div class="text-center">
                <p>@ViewBag.TotalScore</p>
            </div>
            <div>
                <a asp-action="NextRound">New Game</a>
            </div>
        </div>
    </div>

CountDownShow/Views/Dictionary/Index.cshtml
@using CountDownShow.Models
@model Dictionary

<div class="text-center">
    <div class="text-center">
        <div class="text-center">
            <h2 class="text-center">@await Component.InvokeAsync("Score")</h2>
            <p>@ViewBag.welcome</p>
            <p>@ViewBag.nineWord</p>
            <form asp-action="AddNineWords">
                <div>
                    <div>
                        <input asp-for="NineWord" />
                    </div>
                </div>
                <br />
                <div>
                    <div>
                        <button type="submit" class="btn btn-primary">submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

CountDownShow/Views/Dictionary/Result.cshtml
@using CountDownShow.Models

    <div class="text-center">
        <div class="text-center">
            <div class="text-center">
                <h2 class="text-center">@await Component.InvokeAsync("Score")</h2>
                <p>@ViewBag.answer</p>
                <p>@ViewBag.longestWord</p>
                <p>@ViewBag.roundScore</p>
            </div>
        </div>
        <div>
            <a asp-action="NextRound">NextRound</a>
        </div>
    </div>

CountDownShow/Views/Dictionary/countDown.cshtml
@using CountDownShow.Models
@model Dictionary

<div class="text-center">
    <div class="text-center">
        <div class="text-center">
            <h2 class="text-center">@await Component.InvokeAsync("Score")</h2>
            <p id="vbtext">@ViewBag.text</p>
            <p>you nine words is @ViewBag.nineWord</p>
            <p id="timer">30</p>
        </div>
        <form asp-action="InputAnswer">
            <div>
                <div>
                    <input asp-for="InputWord" />
                </div>
            </div>
            <br />
            <div>
                <div>
                    <button type="submit" class="btn btn-primary">submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    function countTime() {
        var timer = document.getElementById('timer').innerHTML;
        document.getElementById('timer').innerHTML = timer - 1;
        if (document.getElementById('timer').innerHTML == 0) {
            clearInterval(count); 
            document.getElementById('vbtext').innerHTML ="Count down , you should submit";
        }
    }
    var count = setInterval(countTime, 1000);
 </script>

CountDownShow/Views/Shared/Components/Score/Default.cshtml
@model CountDownShow.Models.Score

<div class="text-center">
    <p>Round: @Model.Round Total Score: @Model.TotalScore</p>
</div>

CountDownShow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="css/*" asp-href-exclude="all.min.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="all.min.css" />
    </environment>
</head>
<body>
    <div class=" container ">
        <div class=" row">
            <div class="col-md-2">
                <img asp-append-version="true" alt="Logo" src="~/images/Countdown_title.png" style="height:60px;">
            </div>
            <div class="col-md-10">
                <span class="h2">@ViewBag.Title</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @RenderBody()
        </div>
    </div>
</body>
</html>